spring:
  application:
    name: spring-boot-sample

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    env:
      show-values: always
    configprops:
      show-values: always

---
spring:
  config:
    activate:
      on-profile: srv1
server:
  port: 8081

---
spring:
  config:
    activate:
      on-profile: srv2
server:
  port: 8082
