name: Release & Publish to GitHub Packages

on:
  push:
    tags:
      - '*.*.*'
      - '*.*.*-SNAPSHOT'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Copy Maven settings.xml
      run: |
        env
        mkdir -p ~/.m2
        cp .github/settings.xml ~/.m2/settings.xml


    - name: Publish to GitHub Packages
      run: mvn --batch-mode -P release deploy
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
